import type { Customer } from "./customer.types";

export const customers: Customer[] = [
  {
    id: "C001",
    businessName: "Green Harvest Farms",
    customerType: "SME",
    industry: "Agriculture",
    contactPerson: "Ada Okafor",
    email: "ada@greenharvest.ng",
    phone: "+2348012345678",
    status: "Active",
    dateRegistered: "2026-07-02",
  },
  {
    id: "C002",
    businessName: "Prime Logistics Ltd",
    customerType: "Corporate",
    industry: "Transportation",
    contactPerson: "David Johnson",
    email: "david@primelogistics.ng",
    phone: "+2348098765432",
    status: "Pending",
    dateRegistered: "2026-07-05",
  },
  {
    id: "C003",
    businessName: "Sunrise Medical Centre",
    customerType: "Corporate",
    industry: "Healthcare",
    contactPerson: "Grace Obi",
    email: "grace@sunrisemed.ng",
    phone: "+2348123456789",
    status: "Active",
    dateRegistered: "2026-07-06",
  },
  {
    id: "C004",
    businessName: "Bright Future Schools",
    customerType: "Institutional",
    industry: "Education",
    contactPerson: "Samuel Yusuf",
    email: "samuel@brightfuture.edu.ng",
    phone: "+2348034567890",
    status: "Inactive",
    dateRegistered: "2026-07-08",
  },
  {
    id: "C005",
    businessName: "BlueWave Energy",
    customerType: "Corporate",
    industry: "Energy",
    contactPerson: "Chidinma Eze",
    email: "chioma@bluewave.ng",
    phone: "+2348145678901",
    status: "Active",
    dateRegistered: "2026-07-10",
  },
  {
    id: "C006",
    businessName: "City Transport Services",
    customerType: "Government",
    industry: "Transportation",
    contactPerson: "Ibrahim Musa",
    email: "ibrahim@cts.gov.ng",
    phone: "+2348056789012",
    status: "Pending",
    dateRegistered: "2026-07-12",
  },
  {
    id: "C007",
    businessName: "Fresh Basket Foods",
    customerType: "SME",
    industry: "Agriculture",
    contactPerson: "Esther Bello",
    email: "esther@freshbasket.ng",
    phone: "+2348067890123",
    status: "Active",
    dateRegistered: "2026-07-14",
  },
  {
    id: "C008",
    businessName: "TechNova Solutions",
    customerType: "Corporate",
    industry: "Technology",
    contactPerson: "Michael Adeyemi",
    email: "michael@technova.ng",
    phone: "+2348078901234",
    status: "Inactive",
    dateRegistered: "2026-07-15",
  },
  {
    id: "C009",
    businessName: "Metro Construction",
    customerType: "Corporate",
    industry: "Construction",
    contactPerson: "Peter Nwosu",
    email: "peter@metrobuild.ng",
    phone: "+2348089012345",
    status: "Active",
    dateRegistered: "2026-07-17",
  },
  {
    id: "C010",
    businessName: "Unity Cooperative",
    customerType: "SME",
    industry: "Finance",
    contactPerson: "Fatima Ali",
    email: "fatima@unitycoop.ng",
    phone: "+2348090123456",
    status: "Pending",
    dateRegistered: "2026-07-19",
  },
  {
    id: "C011",
    businessName: "National Water Board",
    customerType: "Government",
    industry: "Utilities",
    contactPerson: "John Ekanem",
    email: "john@nwb.gov.ng",
    phone: "+2348101234567",
    status: "Active",
    dateRegistered: "2026-07-21",
  },
  {
    id: "C012",
    businessName: "Heritage University",
    customerType: "Institutional",
    industry: "Education",
    contactPerson: "Ngozi Umeh",
    email: "ngozi@heritage.edu.ng",
    phone: "+2348112345678",
    status: "Inactive",
    dateRegistered: "2026-07-23",
  },
  {
    id: "C013",
    businessName: "Ocean Foods",
    customerType: "SME",
    industry: "Manufacturing",
    contactPerson: "Victor Afolabi",
    email: "victor@oceanfoods.ng",
    phone: "+2348123456780",
    status: "Active",
    dateRegistered: "2026-07-25",
  },
  {
    id: "C014",
    businessName: "Federal Housing Agency",
    customerType: "Government",
    industry: "Public Service",
    contactPerson: "Amina Garba",
    email: "amina@fha.gov.ng",
    phone: "+2348134567891",
    status: "Pending",
    dateRegistered: "2026-07-28",
  },
];
